### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by zkwsk** [HackYourFuture-CPH/boilerplate-for-fp#133]
Most of our dependencies are managed via NPM which is generally fine, but some times we run into students running some strange version of MySQL and quite commonly that they don't know how to set up password auth in newer versions of MySQL. Providing an (optional) Docker setup for the database would be an easy way to resolve this.

**Comment by senner007** [comment]
You want something different than what we did in fp-class12?

**Comment by zkwsk** [comment]
Docker has been set up.
